# 20210429

데이터 전처리 -> 예측을 통한 결과 및 결과에 맞는 데이터 확보 -> GAN 모델 가져오기 -> GAN 모델 재생성 -> 서비스

모델에서 결과값인 label이 어떻게 나오는지 확인해야할 필요
사진 업로드 및 예측하는 index.html, emotion_prediction을 이용해서 업로드 및 확인 작업 수행

## 갑자기 localhost(http://127.0.0.1)로 접속이 안되는 오류 발생
- %systemroot%\System32\drivers\etc의 hosts에서 127.0.0.1 확인
- 프록시 설정 점검
> 해결 안됨

> 다시 anaconda prompt키고 가상환경 재실행하니 실행 완료

## 업로드 -> resize -> 예측 실행 시 제대로 작동하지 않음

test.py로 테스트
```
import tensorflow as tf
import cv2

model = tf.keras.models.load_model('models/model_best_0_2.h5')

img = cv2.imread('1.jpg')
img = cv2.resize(img, dsize = (48, 48))

img = cv2.imread('1.jpg')
cv2.imshow()
prediction = model.predict(img)
print(prediction)
```

- 실행 오류 h5py의 오류 발생
> 찾아보니 `pip uninstall h5py`로 제거 후 -> `conda install -c anaconda h5py` 로 재설치하면 동작한다고 함.

> 재 설치 후 실행하자 h5py로 인한 문제가 해결되었음

## 업로드 -> resize -> 예측 실행 -> 각각 폴더에 저장하는 것 완료!
[Code]
![image](https://user-images.githubusercontent.com/43158502/116551752-31458d00-a933-11eb-853c-568a934ec300.png)

- 업로드
![image](https://user-images.githubusercontent.com/43158502/116551393-db70e500-a932-11eb-8ac6-a4e22ea43b7a.png)

- 각각 폴더에 저장
![image](https://user-images.githubusercontent.com/43158502/116551357-d14ee680-a932-11eb-8834-9ae95e2b167a.png)

# 향후 진행 방향
- 서버에 연결
- 이미지 캡처를 통한 업로드 구현
- 서버, 업로드한 데이터를 이용한 GAN. 이미지 생성
